spring:
  application:
    name: reactive-app
  r2dbc:
    url: r2dbc:postgresql://ep-nameless-silence-am6npcj1-pooler.c-5.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_1nTSx8sJvPur
    properties:
      sslMode: REQUIRE

api:
  openrouter:
    url: https://openrouter.ai/api/v1
    key: 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
    model: openrouter/free

  mistral:
    url: https://api.mistral.ai/v1
    key: VeeuiQzVhVNNh4b3Hey5Jb8KiBMRJy3Y
    model: mistral-small-latest